stages:
  - test
  - release

test:
  stage: test
  image: golang:1.23
  script:
    - go mod download
    - go build # ensure we can build the provider
    - TF_ACC=1 go test ./... -timeout 5m

release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
  script:
    - goreleaser release --clean
